packages:
  - core
  - core/*
  - app/adapters/*
  - app/*
  - app/storage/*
  - packages/*
  - contracts
  - docs

ignoredBuiltDependencies:
  - electron

onlyBuiltDependencies:
  - better-sqlite3
  - duckdb
  - esbuild
